### PR TITLE
fix #337

### LINKED ISSUE #337: [$40] Fix `total` when fallback to DB in search requests
At the moment if search requst fallbacks to DB, the `total` is calculated in a wrong way, it only returns the number of objects for the current page. While it has to return the number of objects in total for all the pages.

Previously we fixed this issue for `GET /resourceBookings` see https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/ResourceBookingService.js#L649-L656

We have to fix search requests for other endpoints:
- `GET /work-periods`
- `GET /work-period-payments`
- `GET /jobs`
- `GET /jobCandidates`
- `GET /jobCandidates/:jobCandidateId/interviews`
- `GET /taas-roles`

- To make it easier to see from where we get data DB or ES, update `function setResHeaders` https://github.com/topcoder-platform/taas-apis/blob/dev/src/common/helper.js#L787-L813 to also set one more header `X-Data-Source` with values `database` or `elasticsearch`. Note, that we already pass flag `result.fromDb` to this method.
- Provide verifications screens that show that for each of these requests, the `total` returned from ES is the same when returned from DB. 
- To test request from DB, the ES service could be stopped `docker stop tc-taas-elasticsearch`.

### PR DESCRIPTION
**Pull request by xxcxy**
verifications screens: 
Job:
es: https://monosnap.com/file/uQc48PsX3meBTsSPmHe5USLV7vUj0L
db: https://monosnap.com/file/9t2sVwk60IuiGE3JJoLAOFkr4O963s

jobCandidate:
es: https://monosnap.com/file/fc56yIJM0OpYb8p8VVGPoSVTp2eqFp
db: https://monosnap.com/file/b0QoqZGJ00KnIGjrnmKWwrG9QtqUk9

interview:
es: https://monosnap.com/file/JEsbEZwYb03eCf23sVTVpmyvgqEPin
db: https://monosnap.com/file/MiDPNcvnqo2CBFp0TPzOTo2h3jAF0a

workPeroid:
es: https://monosnap.com/file/cy3Myc0iMIbU9mBlT0o0R3PPhPCdjp
db: https://monosnap.com/file/Egb5p4YLAOfN2FlJSOf1hALqiEnOH8

wrokPeroidPayment:
es: https://monosnap.com/file/wv6JAYKmuzKPUCI05jIPEUYV5Z8KYs
db: https://monosnap.com/file/8q5vopLwh26yhwQfTDJ0yQonbvIylA

### CODE REVIEW

File: src/services/WorkPeriodService.js [hunk 1]
```diff
@@ -519,10 +519,11 @@ async function searchWorkPeriods (currentUser, criteria, options = { returnAll:
       required: false
     }]
   }
-  const workPeriods = await WorkPeriod.findAll(queryCriteria)
+  const workPeriods = await WorkPeriod.findAndCountAll(queryCriteria)
+  const total = await WorkPeriod.count({ where: filter })
```
Comment (maxceem) [inline src/services/WorkPeriodService.js:523]: @xxcxy I didn't know such a method exists. I wonder why you didn't use the output from this method and call `await WorkPeriod.count({ where: filter })` anyway below?

Can we just call `findAndCountAll`?

Comment (xxcxy) [reply src/services/WorkPeriodService.js:523]: Strange, I forgot to change this. I tried findAndCountAll, the count returned by this method is wrong.

Comment (eisbilir) [reply src/services/WorkPeriodService.js]: @maxceem @xxcxy
Fyi, `findAndCountAll` is safe when we don't have `include` option in query. Otherwise it gives wrong count number and becomes complex to solve.

Comment (maxceem) [reply src/services/WorkPeriodService.js]: Thanks @eisbilir. I think than it’s better not use it, because if we use it one place then new developer can copy paste it to a new place with include and would not notice that it works incorrectly there.

**Review by maxceem — APPROVED** [review]
@xxcxy looks good.
